version: '3'
services:
  shrine-nginx:
    container_name: "shrine-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - shrine-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  shrine-app:
    container_name: "shrine-app"
    build:
      context: ./docker/php
    depends_on:
      - shrine-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  shrine-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "shrine-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shrine
    ports:
      - 3306:3306

  shrine-redis:
    image: redis:alpine
    container_name: "shrine-redis"
    ports:
      - 16379:6379
